# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogentries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dt_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='dt_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postcomponent',
            name='dt_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
